SELECT ITEM.ITEM_CD
	 , ITEM.ITEM_NM
	 , ITEM.ITEM_ATTR01_CD
	 , ITEM.ITEM_ATTR02_CD
	 , ITEM.ITEM_ATTR03_CD
	 , ITEM.ITEM_ATTR04_CD
	 , ITEM.ITEM_ATTR01_NM
	 , ITEM.ITEM_ATTR02_NM
	 , ITEM.ITEM_ATTR03_NM
	 , ITEM.ITEM_ATTR04_NM
FROM VIEW_I002040 ITEM
WHERE 1=1
  AND ITEM.ITEM_ATTR01_CD IN (:VS_CB_BIZ_CD)
  AND ITEM.ITEM_ATTR02_CD IN (:VS_CB_LINE_CD)
  AND ITEM.ITEM_ATTR03_CD IN (:VS_CB_BRAND_CD)
  AND ITEM.ITEM_TYPE_CD = 'FERT'
  AND ITEM.USE_YN 		= 'Y'
ORDER BY ITEM.ITEM_CD

SELECT * FROM M4S_I002011 WHERE COMM_CD LIKE 'ITEM_GUBUN03'

SELECT * FROM M4S_I002172
WHERE DATA_VRSN_CD = '20190114-20220109'

delete
FROM M4S_I204050
WHERE 1=1
  AND PROJECT_CD = :VS_P_PROJECT_CD
  AND SALES_MGMT_VRSN_ID = :VS_CB_SALES_MGMT_VRSN
  AND ITEM_CD ='5101209'
  AND LEFT(SALES_MGMT_CD,7) = '1111101'


SELECT SMC.PROJECT_CD
    , SMC.SALES_MGMT_VRSN_ID
    , SMC.SALES_MGMT_CD
    , SHC.SALES_MGMT_NM
    , SHM.USER_CD
FROM M4S_I204050 SMC
  JOIN M4S_I204030 SHC
    ON SMC.PROJECT_CD = SHC.PROJECT_CD
   AND SMC.SALES_MGMT_VRSN_ID = SHC.SALES_MGMT_VRSN_ID
   AND SMC.SALES_MGMT_CD = SHC.SALES_MGMT_CD
  JOIN M4S_I204040 SHM
    ON SMC.PROJECT_CD = SHM.PROJECT_CD
   AND SMC.SALES_MGMT_VRSN_ID = SHM.SALES_MGMT_VRSN_ID
   AND SMC.SALES_MGMT_CD = SHM.LINK_SALES_MGMT_CD
WHERE 1=1
  AND SMC.PROJECT_CD = :VS_P_PROJECT_CD
  AND SMC.SALES_MGMT_VRSN_ID = :VS_CB_SALES_MGMT_VRSN
  AND SMC.ITEM_CD IN (:VS_P_ITEM_CD)
  AND SMC.USE_YN 	= 'Y'
GROUP BY SMC.PROJECT_CD
    , SMC.SALES_MGMT_VRSN_ID
    , SMC.SALES_MGMT_CD
    , SHC.SALES_MGMT_NM
    , SHM.USER_CD


DELETE FROM M4S_I204050
WHERE PROJECT_CD			= 'ENT001'
  AND SALES_MGMT_VRSN_ID	= '202112_V0'
  AND ITEM_CD				= '5101209'
;


SELECT * FROM M4S_I001041