SELECT ITEM.ITEM_CD
	 , ITEM.ITEM_NM
	 , ITEM.ITEM_ATTR01_CD
	 , ITEM.ITEM_ATTR02_CD
	 , ITEM.ITEM_ATTR03_CD
	 , ITEM.ITEM_ATTR04_CD
	 , ITEM.ITEM_ATTR01_NM
	 , ITEM.ITEM_ATTR02_NM
	 , ITEM.ITEM_ATTR03_NM
	 , ITEM.ITEM_ATTR04_NM
FROM VIEW_I002040 ITEM
WHERE 1=1
  AND ITEM.ITEM_ATTR01_CD IN (:VS_CB_BIZ_CD)
  AND ITEM.ITEM_ATTR02_CD IN (:VS_CB_LINE_CD)
  AND ITEM.ITEM_ATTR03_CD IN (:VS_CB_BRAND_CD)
  AND ITEM.ITEM_TYPE_CD = 'FERT'
  AND ITEM.USE_YN 		= 'Y'
ORDER BY ITEM.ITEM_CD


SELECT * FROM M4S_I002011 WHERE COMM_CD LIKE 'ITEM_GUBUN03'


SELECT *
FROM M4S_I204050
WHERE 1=1
  AND PROJECT_CD = :VS_P_PROJECT_CD
  AND SALES_MGMT_VRSN_ID = :VS_CB_SALES_MGMT_VRSN
  AND ITEM_CD ='5142490'


SELECT * FROM M4S_I002172
WHERE DATA_VRSN_CD = '20190114-20220109'



SELECT CONVERT(CHAR, CONVERT(DATE, SALES.YYMMDD), 121) AS DATE
     , QTY_SCALING AS REF_VAL1
     , ROUND(VAL_SCALING, 4) AS REF_VAL2
FROM (
         SELECT PROJECT_CD
              , DATA_VRSN_CD
              , YYMMDD
              , QTY_SCALING
         FROM M4S_I002172
         WHERE 1 = 1
           AND DATA_VRSN_CD 	= '20190114-20220109'
           AND DIVISION_CD  	= 'BIZ_CD'
           AND ITEM_ATTR01_CD 	= 'P1'


     ) SALES
LEFT OUTER JOIN (
					SELECT EXG.PROJECT_CD
						, EXG.IDX_CD
						, EXG.IDX_DTL_CD
						, YYMM AS YYMMDD
                        , CASE WHEN MAX_VAL = MIN_VAL THEN 0
							   ELSE(REF_VAL - MIN_VAL) / (MAX_VAL - MIN_VAL) END AS VAL_SCALING
					FROM (
							SELECT PROJECT_CD
									, IDX_CD
									, IDX_DTL_CD
									, IDX_DTL_NM
									, YYMM
									, REF_VAL
							FROM M4S_O110710
							WHERE 1=1
								AND IDX_CD 		= 'GSR_SUM'
								AND IDX_DTL_CD 	= '105'
						) EXG
					LEFT OUTER JOIN (
						SELECT PROJECT_CD
							, IDX_CD
							, IDX_DTL_CD
							, MIN(REF_VAL) AS MAX_VAL
							, MAX(REF_VAL) AS MIN_VAL
						FROM M4S_O110710
						WHERE 1 = 1
							AND IDX_CD 		= 'GSR_SUM'
							AND IDX_DTL_CD 	= '105'
							AND YYMM BETWEEN (SELECT OPTION_VAL FROM M4S_I001020 WHERE OPTION_CD = 'RST_START_DAY')
										AND (SELECT OPTION_VAL FROM M4S_I001020 WHERE OPTION_CD = 'RST_END_DAY')
						GROUP BY PROJECT_CD
								, IDX_CD
								, IDX_DTL_CD
                ) MM
                ON EXG.PROJECT_CD 	= MM.PROJECT_CD
               AND EXG.IDX_CD 		= MM.IDX_CD
               AND EXG.IDX_DTL_CD 	= MM.IDX_DTL_CD
    ) EXG
 ON SALES.PROJECT_CD = EXG.PROJECT_CD
AND SALES.YYMMDD 	 = EXG.YYMMDD
ORDER BY SALES.YYMMDD
