SELECT SALES_ITEM.ITEM_CD SKU_CD
	 , ITEM.ITEM_NM SKU_NM
	 , ITEM.ITEM_ATTR01_NM BIZ_NM
	 , ITEM.ITEM_ATTR02_NM LINE_NM
	 , ITEM.ITEM_ATTR03_NM BRAND_NM
	 , ITEM.ITEM_ATTR04_NM ITEM_NM
FROM M4S_I204050 SALES_ITEM
  JOIN VIEW_I002040 ITEM
   ON SALES_ITEM.ITEM_CD = ITEM.ITEM_CD
  AND ITEM.USE_YN = 'Y'
WHERE SALES_ITEM.PROJECT_CD = :VS_P_PROJECT_CD
  AND SALES_ITEM.SALES_MGMT_VRSN_ID = :VS_CB_SALES_MGMT_VRSN
  AND :VN_SALES_HIERARCHY = :VS_P_SALES_MGMT_CD
  AND SALES_ITEM.USE_YN = 'Y'
  AND (ITEM.ITEM_CD LIKE '%' + :VS_TB_ITEM_CD + '%' OR ITEM.ITEM_NM LIKE '%' + :VS_TB_ITEM_CD + '%')

SELECT distinct SOLD_CUST_GRP_CD FROM m4s_i002170

select *
from m4s_i204050


select * FROM M4S_I002011
	 WHERE COMM_CD = 'SP_HORIZON_CD'
	   AND COMM_DTL_CD = 'HORIZON_CD'

SELECT * FROM M4S_O201010_1207

SELECT * FROM M4S_O201001 WHERE DP_VRSN_ID = 'SP_2021W49.01' AND PLAN_WEEK NOT IN ('W53','W06')


select distinct cust_grp_cd
from M4S_I002060
where CUST_CD in (SELECT distinct SOLD_CUST_GRP_CD FROM m4s_i002170)


SELECT RST.PROJECT_CD
    , RST.SOLD_CUST_GRP_CD
    , RST.ITEM_CD
FROM M4S_I002170 RST
WHERE PROJECT_CD = 'ENT001'
    AND DIVISION_CD = 'SELL_IN'
    AND RST.YYMMDD BETWEEN DATEADD(MM, DATEDIFF(MM,0, DATEADD(MONTH, -3, CONVERT(DATE, :V_YYMMDD))) ,0) AND DATEADD(MM, DATEDIFF(MM,0,CONVERT(DATE, :V_YYMMDD)) ,0) - 1
GROUP BY RST.PROJECT_CD
    , RST.SOLD_CUST_GRP_CD
    , RST.ITEM_CD


SELECT SMC.PROJECT_CD
    , SUBSTRING(:V_YYMMDD,1,6) + '_V0'
    , SMC.SALES_MGMT_CD
    , SMC.ITEM_CD
    , SMC.USER_CD
    , 'N'
    , 'Y'
    , NULL
    , 'SYSTEM'
    , GETDATE()
    , NULL
    , NULL
FROM M4S_I204050 SMC
JOIN (
    SELECT CUST.PROJECT_CD
         , CUST.CUST_GRP_CD
         , RST.ITEM_CD
    FROM M4S_I002060 CUST
             JOIN (SELECT PROJECT_CD
                        , SOLD_CUST_GRP_CD
                        , ITEM_CD
                   FROM M4S_I002170
                   WHERE PROJECT_CD = 'ENT001'
                     AND DIVISION_CD = 'SELL_IN'
                     AND YYMMDD BETWEEN DATEADD(MM, DATEDIFF(MM, 0, DATEADD(MONTH, -3, CONVERT(DATE, :V_YYMMDD))),0) AND DATEADD(MM, DATEDIFF(MM, 0, CONVERT(DATE, :V_YYMMDD)), 0)
                   GROUP BY PROJECT_CD
                          , SOLD_CUST_GRP_CD
                          , ITEM_CD) RST
                  ON CUST.PROJECT_CD = RST.PROJECT_CD
                      AND CUST.CUST_CD = RST.SOLD_CUST_GRP_CD
) RST
ON SMC.PROJECT_CD = RST.PROJECT_CD
AND SUBSTRING(SMC.SALES_MGMT_CD,8,4) = RST.CUST_GRP_CD
AND SMC.ITEM_CD = RST.ITEM_CD
WHERE 1=1
  AND SMC.PROJECT_CD = :V_PROJECT_CD
  AND SMC.SALES_MGMT_VRSN_ID = '202111_V0'--FORMAT(DATEADD(MONTH, -1, CONVERT(DATE, :V_YYMMDD)),'yyyyMM') + '_V0'




SELECT DATEADD(MM, DATEDIFF(MM,0, DATEADD(MONTH, -3, CONVERT(DATE, '20211202'))) ,0)
    ,DATEADD(MM, DATEDIFF(MM,0,CONVERT(DATE, '20211202')) ,0) - 1

SELECT DATEDIFF(MM,0, GETDATE())

SELECT * FROM M4S_I204040 WHERE SALES_MGMT_VRSN_ID='202111_V0'
SELECT * FROM M4S_I204030 WHERE SALES_MGMT_VRSN_ID='202109_V0'
                            AND SUBSTRING(SALES_MGMT_CD,1,2) = '11'

SELECT T1.*
FROM M4S_I204020 T1
LEFT JOIN M4S_I204030 T2
ON T1.PROJECT_CD = T2.PROJECT_CD
AND T1.SALES_MGMT_VRSN_ID = T2.SALES_MGMT_VRSN_ID
AND T1.SALES_MGMT_TYPE_CD = T2.SALES_MGMT_TYPE_CD
AND T1.LINK_SALES_MGMT_CD = SUBSTRING(T2.SALES_MGMT_CD,8,4)
WHERE T2.SALES_MGMT_CD IS NULL
AND T1.SALES_MGMT_VRSN_ID='202111_V0'
AND T1.SALES_MGMT_TYPE_CD = 'SP1'
AND T1.LINK_SALES_MGMT_CD LIKE '10%'
--WHERE SALES_MGMT_VRSN_ID='202111_V0'


 SELECT * FROM M4S_I204030
 WHERE SALES_MGMT_VRSN_ID='202111_V0' AND LINK_SALES_MGMT_CD = '101'

 WHERE LINK_SALES_MGMT_NM LIKE '도봉%'


SELECT SALES_ITEM.ITEM_CD SKU_CD
	 , ITEM.ITEM_NM SKU_NM
	 , ITEM.ITEM_ATTR01_NM BIZ_NM
	 , ITEM.ITEM_ATTR02_NM LINE_NM
	 , ITEM.ITEM_ATTR03_NM BRAND_NM
	 , ITEM.ITEM_ATTR04_NM ITEM_NM
FROM M4S_I204050 SALES_ITEM
  JOIN VIEW_I002040 ITEM
   ON SALES_ITEM.ITEM_CD = ITEM.ITEM_CD
  AND ITEM.USE_YN = 'Y'
WHERE SALES_ITEM.PROJECT_CD = :VS_P_PROJECT_CD
  AND SALES_ITEM.SALES_MGMT_VRSN_ID = :VS_CB_SALES_MGMT_VRSN
  AND :VN_SALES_HIERARCHY = :VS_P_SALES_MGMT_CD
  AND SALES_ITEM.USE_YN = 'Y'
  AND (ITEM.ITEM_CD LIKE '%' + :VS_TB_ITEM_CD + '%' OR ITEM.ITEM_NM LIKE '%' + :VS_TB_ITEM_CD + '%')
GROUP BY SALES_ITEM.ITEM_CD
	 , ITEM.ITEM_NM
	 , ITEM.ITEM_ATTR01_NM
	 , ITEM.ITEM_ATTR02_NM
	 , ITEM.ITEM_ATTR03_NM
	 , ITEM.ITEM_ATTR04_NM


SELECT * FROM M4S_I204050
 WHERE SALES_MGMT_VRSN_ID='202111_V0'
AND ITEM_CD = '5100081'


SELECT * FROM M4S_I204050


UPDATE M4S_I204050
SET   USE_YN = 'N'
	, DEL_YN = 'Y'
WHERE   PROJECT_CD			= 'ENT001'
    AND SALES_MGMT_VRSN_ID	= '202111_V0'
    AND SUBSTRING(SALES_MGMT_CD,1,4)		= '1111'
    AND ITEM_CD				= '5100081'



SELECT * FROM M4S_I204050
-- ORDER BY SALES_MGMT_VRSN_ID
WHERE SALES_MGMT_VRSN_ID = '202106_V0'

SELECT SMC.PROJECT_CD
    , :V_SALES_MGMT_VRSN_ID
    , SMC.SALES_MGMT_CD
    , SMC.ITEM_CD
    , SMC.USER_CD
    , 'N'
    , 'Y'
    , NULL
    , 'SYSTEM'
    , GETDATE()
    , NULL
    , NULL
    FROM M4S_I204050 SMC
    JOIN (
            SELECT CUST.PROJECT_CD
                 , CUST.CUST_GRP_CD
                 , RST.ITEM_CD
            FROM M4S_I002060 CUST
                     JOIN (
                             SELECT PROJECT_CD
                                    , SOLD_CUST_GRP_CD
                                    , ITEM_CD
                               FROM M4S_I002170
                               WHERE PROJECT_CD = :V_PROJECT_CD
                                 AND DIVISION_CD = 'SELL_IN'
                                 AND YYMMDD BETWEEN DATEADD(MM, DATEDIFF(MM, 0, DATEADD(MONTH, -3, CONVERT(DATE, SUBSTRING(:V_SALES_MGMT_VRSN_ID, 1, 6) + '01'))),0) AND DATEADD(MM, DATEDIFF(MM, 0, CONVERT(DATE, SUBSTRING(:V_SALES_MGMT_VRSN_ID, 1, 6) + '01')), 0)
                               GROUP BY PROJECT_CD
                                      , SOLD_CUST_GRP_CD
                                      , ITEM_CD
                         ) RST
                          ON CUST.PROJECT_CD = RST.PROJECT_CD
                              AND CUST.CUST_CD = RST.SOLD_CUST_GRP_CD
            GROUP BY CUST.PROJECT_CD
                 , CUST.CUST_GRP_CD
                 , RST.ITEM_CD
        ) RST
    ON SMC.PROJECT_CD = RST.PROJECT_CD
    AND SUBSTRING(SMC.SALES_MGMT_CD,8,4) = RST.CUST_GRP_CD
    AND SMC.ITEM_CD = RST.ITEM_CD
    WHERE 1=1
      AND SMC.PROJECT_CD = :V_PROJECT_CD
      AND SMC.SALES_MGMT_VRSN_ID = '202111_V0'


SELECT * FROM M4S_O110300 WHERE RANK = 'ADD'



SELECT RSLT.DATA_VRSN_CD
     , RSLT.DIVISION_CD
     , RSLT.FKEY
     , RSLT.TEST_VRSN_CD
     , RSLT.CUST_GRP_CD
     , RSLT.CUST_GRP_NM
     , RSLT.ITEM_ATTR01_CD
     , RSLT.ITEM_ATTR01_NM
     , RSLT.ITEM_ATTR02_CD
     , RSLT.ITEM_ATTR02_NM
     , RSLT.ITEM_ATTR03_CD
     , RSLT.ITEM_ATTR03_NM
     , RSLT.ITEM_ATTR04_CD
     , RSLT.ITEM_ATTR04_NM
     , RSLT.ITEM_CD
     , RSLT.ITEM_NM
	 , RSLT.WEEK
	 , CAL.YYMMDD
     , ROUND(RSLT.SALES,0) RST_SALES_QTY
     , ROUND(RSLT.PRED,0) RESULT_SALES
  FROM M4S_O110620 RSLT
  JOIN M4S_I002030 CAL
  ON  RSLT.PROJECT_CD 	= CAL.PROJECT_CD
  AND RSLT.YY		 	= CAL.YY
  AND RSLT.WEEK 		= CAL.WEEK
  AND CAL.YYMMDD		= CAL.START_WEEK_DAY
WHERE 1=1
  AND RSLT.PROJECT_CD = :VS_PROJECT_CD
  AND RSLT.DATA_VRSN_CD = :VS_CB_DATA_VRSN_CD
  AND RSLT.DIVISION_CD = :VS_CB_DIVISION
  AND RSLT.FKEY = :VS_CB_LVL
  AND RSLT.TEST_VRSN_CD = :VS_CB_TEST_VRSN