        SELECT :V_PROJECT_CD AS PROJECT_CD
			 , T1.DATA_VRSN_CD
			 , T1.DIVISION_CD
			 , :V_CLASSIFY_CD AS CLASSIFY_CD
			 , 'NEW' AS ITEM_TYPE_CD
			 , T1.STAT_CD
			 , T1.WEEK
			 , T1.YYMMDD
			 , SUM(T1.RESULT_SALES) * :V_RATE_NEW / 100 AS RESULT_SALES
			 , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM
			-- , CREATE_USER_CD
			-- , CREATE_DATE
			 , :V_MODIFY_USER_CD AS CREATE_USER_CD
			 , GETDATE() AS CREATE_DATE
			 , :V_MODIFY_USER_CD AS MODIFY_USER_CD
			 , GETDATE() AS MODIFY_DATE
		 FROM M4S_O110600 T1
          JOIN VIEW_I002040 ITEM
            ON ITEM.ITEM_CD = :V_ITEM_CD
		WHERE 1=1
		  AND T1.DATA_VRSN_CD = :V_DATA_VRSN_CD
		  AND T1.DIVISION_CD = :V_DIVISION_CD
		  AND T1.FKEY LIKE '%C1-P5%'    -- Exception (fix the data level)
		  AND T1.ITEM_CD = :V_SIM_ITEM_CD
		GROUP BY T1.DATA_VRSN_CD
			 , T1.DIVISION_CD
			 , T1.STAT_CD
			 , T1.WEEK
			 , T1.YYMMDD
			 , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM


SELECT * FROM M4S_O110400 WHERE 1=1

        SELECT * FROM M4S_O110400_BACK_1201

SELECT * FROM M4S_O110600
WHERE 1=1
		  AND DATA_VRSN_CD = :V_DATA_VRSN_CD
		  AND DIVISION_CD = :V_DIVISION_CD
		  AND FKEY LIKE '%C1-P5%'    -- Exception (fix the data level)
          AND ITEM_NM LIKE '%초코파이%'
		  AND ITEM_CD = :V_SIM_ITEM_CD

INSERT INTO M4S_O110300
SELECT *  FROM M4S_O110300_BACK WHERE 1=1


SELECT :V_PROJECT_CD AS PROJECT_CD
			 , RESULT.DATA_VRSN_CD
			 , RESULT.DIVISION_CD
			 , :V_CLASSIFY_CD AS CLASSIFY_CD
			 , 'REV' AS ITEM_TYPE_CD
			 , RESULT.STAT_CD
			 , RESULT.WEEK
			 , RESULT.YYMMDD
			 , SUM(RESULT.RESULT_SALES) * :V_RATE / 100 AS RESULT_SALES
			 , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM
			 , :V_MODIFY_USER_CD AS CREATE_USER_CD
			 , GETDATE() AS CREATE_DATE
			 , :V_MODIFY_USER_CD AS MODIFY_USER_CD
			 , GETDATE() AS MODIFY_DATE
		 FROM M4S_O110600 RESULT
		    JOIN VIEW_I002040 ITEM
		      ON ITEM.ITEM_CD = :V_ITEM_CD
		WHERE 1=1
		  AND RESULT.DATA_VRSN_CD = :V_DATA_VRSN_CD
		  AND RESULT.DIVISION_CD = :V_DIVISION_CD
		  AND RESULT.ITEM_CD = :V_SIM_ITEM_CD
        GROUP BY RESULT.DATA_VRSN_CD
			 , RESULT.DIVISION_CD
			 , RESULT.STAT_CD
			 , RESULT.WEEK
			 , RESULT.YYMMDD
             , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM



SELECT DATA_VRSN_CD
	   ,DIVISION_CD
	   ,CLASSIFY_CD
	 --  ,ITEM_TYPE_CD
   	   ,CASE
		WHEN ITEM_TYPE_CD = 'NEW' THEN '신제품'
		WHEN ITEM_TYPE_CD = 'OLD' THEN '기존제품'
		WHEN ITEM_TYPE_CD = 'REV' THEN '개선제품'
		END AS ITEM_TYPE_CD_NM
	   ,RESULT.STAT_CD
	   ,ALGO.STAT_NM
	   ,WEEK
	   ,YYMMDD
	   ,SUBSTRING(YYMMDD,0,5) AS YY
	   ,SUBSTRING(YYMMDD,0,7) AS YYMM
	   ,RESULT_SALES
	   ,ITEM_ATTR01_NM
	   ,ITEM_ATTR02_NM
   	   ,ITEM_ATTR03_NM
   	   ,ITEM_ATTR04_NM
	   ,ITEM_CD
	   ,ITEM_NM
	   ,NEW_ITEM_CD
	   --,ITEM.ITEM_NM NEW_ITEM_NM
FROM M4S_O110400 RESULT
LEFT OUTER JOIN ( --알고리즘명 추출
  				   SELECT STAT_CD
						, STAT_NM
					 FROM M4S_I103010
					WHERE 1=1
					  AND DIVISION_CD = 'FCST'
					  AND USE_YN = 'Y'
				  ) ALGO
	ON RESULT.STAT_CD = ALGO.STAT_CD
JOIN M4S_I002040 ITEM
  ON RESULT.NEW_ITEM_CD = ITEM.ITEM_CD
WHERE 1=1
AND CLASSIFY_CD = :VS_CLASSIFY_CD
AND NEW_ITEM_CD = :VS_ITEM_CD
AND DATA_VRSN_CD = :VS_CB_DATA_VRSN_CD
AND DIVISION_CD = :VS_DIVISION_CD


select * from m4s_i002170 where yy = '2021'

select * from M4S_I204022 WHERE MEASURE_CD = 'SP1_M012'

        SELECT * FROM M4S_I002011 WHERE COMM_CD = 'MEASURE_CD'

select * from m4s_i002170

select * from m4s_i002173

SELECT * FROM M4S_I002041

SELECT  * FROM tmp_M4S_i204100

SELECT * FROM M4S_O111600

SELECT * FROM TMP_M4S_I204100

select * from m4s_o201001 WHERE ITEM_CD = '6120183' AND SALES_MGMT_CD = '11121021068' ORDER BY MODIFY_DATE DESC


SELECT * FROM M4S_O201001 T1
JOIN TMP_M4S_I204100 EVN
ON T1.PLAN_YYMMDD BETWEEN DATEADD(DAY, -6, EVN.PLAN_FROM_YYMMDD) AND EVN.PLAN_TO_YYMMDD
AND T1.ITEM_CD = EVN.ITEM_CD
AND SUBSTRING(T1.SALES_MGMT_CD, 8, 4) = EVN.CUST_GRP_CD
WHERE 1=1
AND T1.PROJECT_CD = 'ENT001'
             AND T1.DP_VRSN_ID = 'SP_2021W49.01'
             AND T1.USER_CD = 'dev07'
             AND SUBSTRING(T1.SALES_MGMT_CD,1,2) = '11'
             AND SUBSTRING(T1.SALES_MGMT_CD, 8,4) = '1068'



SELECT PLAN_SP1.PROJECT_CD
              ,PLAN_SP1.DP_VRSN_ID
              ,PLAN_SP1.SALES_MGMT_CD
              ,PLAN_SP1.ITEM_CD
              ,PLAN_SP1.USER_CD
              ,CAL.YYMMDD
              ,CAL.WEEK
              ,CAL.PART_WEEK
              ,PLAN_SP1.PLAN_YYMM
              ,PLAN_SP1.PLAN_YY
              ,PLAN_SP1.DP_QTY
              ,PLAN_SP1.DP_PRICE
              ,PLAN_SP1.USER_CD MODIFY_USER_CD
              ,GETDATE()

SELECT SMC.PROJECT_CD
     , 'SP_2021W49.01'
     , SMC.SALES_MGMT_CD
     , SMC.ITEM_CD
     , SMC.USER_CD
     , CAL.YYMMDD
     , CAL.WEEK
     , CAL.PART_WEEK
     , CAL.YYMM
     , CAL.YY
     , 0
     , PLAN_SP1.DP_PRICE
     , SMC.USER_CD MODIFY_USER_CD
     , GETDATE()
FROM M4S_I204050 SMC
    JOIN (SELECT CAL.PROJECT_CD
                        , YYMMDD
                        , YYMM
                        , YY
                        , WEEK
                        , PART_WEEK
                    FROM M4S_I002030 CAL
                        , (SELECT PLAN_FROM_YYMMDD FROM M4S_O201010 WHERE DP_VRSN_ID = 'SP_2021W49.01') START_DAY
                    WHERE YYMMDD = START_MONTH_DAY
                      AND YYMM BETWEEN FORMAT(DATEADD(MONTH, 1,DATEADD(WEEK, 3, CONVERT(DATE, START_DAY.PLAN_FROM_YYMMDD))),'yyyyMM') AND FORMAT(DATEADD(MONTH, 2,DATEADD(WEEK, 3, CONVERT(DATE, START_DAY.PLAN_FROM_YYMMDD))),'yyyyMM')
                ) CAL
    ON SMC.PROJECT_CD = CAL.PROJECT_CD
    JOIN (
              SELECT PROJECT_CD
                      ,DP_VRSN_ID
                      ,SALES_MGMT_CD
                      ,ITEM_CD
                      ,USER_CD
                      ,MAX(DP_PRICE) DP_PRICE
                  FROM M4S_O201001
                 WHERE 1=1
                   AND PROJECT_CD = 'ENT001'
                   AND DP_VRSN_ID = 'SP_2021W49.01'
                   AND SUBSTRING(SALES_MGMT_CD,1,2) = SUBSTRING('11_102',1,2)
                   AND SUBSTRING(SALES_MGMT_CD,5,3) = SUBSTRING('11_102',4,3)
                   AND PLAN_YYMMDD >= (SELECT PLAN_FROM_YYMMDD FROM M4S_O201010 WHERE DP_VRSN_ID = 'SP_2021W49.01')
                 GROUP BY PROJECT_CD
                      ,DP_VRSN_ID
                      ,SALES_MGMT_CD
                      ,ITEM_CD
                      ,USER_CD
            ) PLAN_SP1
    ON SMC.PROJECT_CD = PLAN_SP1.PROJECT_CD
    AND SMC.SALES_MGMT_CD = PLAN_SP1.SALES_MGMT_CD
    AND SMC.ITEM_CD = PLAN_SP1.ITEM_CD
    AND SMC.USER_CD = PLAN_SP1.USER_CD
WHERE SMC.PROJECT_CD = 'ENT001'
  AND SMC.SALES_MGMT_VRSN_ID = (SELECT SALES_MGMT_VRSN_ID FROM M4S_O201010 WHERE DP_VRSN_ID = 'SP_2021W49.01')
  AND SUBSTRING(SMC.SALES_MGMT_CD,1,2) = SUBSTRING('11_102',1,2)
  AND SUBSTRING(SMC.SALES_MGMT_CD,5,3) = SUBSTRING('11_102',4,3)


INSERT INTO M4S_O201002( PROJECT_CD
                                ,DP_VRSN_ID
                                ,SALES_MGMT_CD
                                ,ITEM_CD
                                ,USER_CD
                                ,PLAN_YYMMDD
                                ,PLAN_WEEK
                                ,PLAN_PART_WEEK
                                ,PLAN_YYMM
                                ,PLAN_YY
                                ,DP_QTY
                                ,DP_PRICE
                                ,CREATE_USER_CD
                                ,CREATE_DATE )

          FROM (SELECT PROJECT_CD
                        , YYMMDD
                        , YYMM
                        , YY
                        , WEEK
                        , PART_WEEK
                    FROM M4S_I002030 CAL
                    WHERE YYMMDD = START_MONTH_DAY
                ) CAL
            JOIN (
                    SELECT COUNT(*) CNT
                    FROM M4S_I002030 CAL
                    WHERE START_MONTH_DAY = (SELECT PLAN_FROM_YYMMDD FROM M4S_O201010 WHERE DP_VRSN_ID = 'SP_2021W49.01')
                ) CAL_CNT
            ON 1=1
            JOIN (
                    SELECT PLAN_FROM_YYMMDD
                    FROM M4S_O201010
                    WHERE DP_VRSN_ID = 'SP_2021W49.01'
                ) START_DAY
            ON 1=1
--             LEFT JOIN (SELECT PROJECT_CD
--                       ,DP_VRSN_ID
--                       ,SALES_MGMT_CD
--                       ,ITEM_CD
--                       ,USER_CD
--                       ,PLAN_YYMM
--                       ,PLAN_YY
--                       ,SUM(DP_QTY) DP_QTY
--                       ,MAX(DP_PRICE) DP_PRICE
--                   FROM M4S_O201001
--                  WHERE 1=1
--                    AND PROJECT_CD = 'ENT001'
--                    AND DP_VRSN_ID = 'SP_2021W49.01'
--                    AND SUBSTRING(SALES_MGMT_CD,1,2) = SUBSTRING('11_102',1,2)
--                    AND SUBSTRING(SALES_MGMT_CD,5,3) = SUBSTRING('11_102',4,3)
--                    AND PLAN_YYMMDD >= (SELECT PLAN_FROM_YYMMDD FROM M4S_O201010 WHERE DP_VRSN_ID = 'SP_2021W49.01')
--                  GROUP BY PROJECT_CD
--                       ,DP_VRSN_ID
--                       ,SALES_MGMT_CD
--                       ,ITEM_CD
--                       ,USER_CD
--                       ,PLAN_YYMM
--                       ,PLAN_YY
--                       ,USER_CD) PLAN_SP1
--             ON PLAN_SP1.PROJECT_CD = CAL.PROJECT_CD
--             AND PLAN_SP1.PLAN_YYMM = CAL.YYMM
--             AND PLAN_SP1.PLAN_YY = CAL.YY
         WHERE 1=1
           AND CAL.PROJECT_CD = 'ENT001'
           AND CAL.YYMMDD BETWEEN DATEADD(MM, DATEDIFF(MM,0, CONVERT(DATE, START_DAY.PLAN_FROM_YYMMDD)) ,0) AND DATEADD(MONTH,CASE WHEN CAL_CNT.CNT = 0 THEN 3 ELSE 4 END,START_DAY.PLAN_FROM_YYMMDD)


SELECT PLAN_SP1.PROJECT_CD
FROM TMP_M4S_O201001_1206 PLAN_SP1



SELECT * --INTO TMP_M4E_O402130
        FROM TMP_M4E_O402130
       ORDER BY RES_CD, YYMMDD, ST_DT


SELECT * FROM TMP_M4E_O402130_1206

SELECT * FROM TMP_M4E_O402130

SELECT * FROM M4E_O402110

SELECT NULL
              ,NULL
              ,T3.RES_CD
              ,T3.PLANT_CD
              ,T3.ITEM_CD
              ,ROUND(T1.START_TIME,0) AS START_TIME
              ,ROUND(T1.START_TIME + T2.PROD_QTY * T3.CAPA_USE_RATE,0) AS END_TIME
              ,T2.PROD_QTY
              ,T3.CAPA_USE_RATE
          fROM M4E_O402110 T1
              ,M4E_O402120 T2
              ,M4S_I305110 T3
        WHERE T1.ROUTE_CD = T2.ROUTE_CD
           AND T1.ENG_ITEM_CD = T2.ENG_ITEM_CD
           AND PROD_QTY > 0
           AND T1.ROUTE_CD = T3.RES_CD+'@'+T3.PLANT_CD
           AND T1.ENG_ITEM_CD = T3.ITEM_CD+'@'+T3.PLANT_CD
           AND T3.USE_YN = 'Y'
           AND T1.TIME_INDEX = 1
           AND T1.TIME_INDEX = T2.TIME_INDEX



SELECT DATEADD(DAY, CASE WHEN CAL1.CNT = 0 THEN 3 ELSE 0 END , GETDATE()) FROM (SELECT COUNT(*) CNT FROM M4S_I002030 WHERE START_MONTH_DAY = FORMAT(GETDATE(),'yyyyMMdd')) CAL1