select * from m4s_i204100

select * from m4s_i002041 WHERE PRICE_QTY_UNIT_CD = 'BOX'

SELECT CAL.YYMMDD
      ,CAL.WEEK
FROM M4S_I002030 CAL
WHERE CAL.PROJECT_CD = 'ENT001'
  AND CAL.YY = '2021'
  AND CAL.YYMMDD = CAL.START_WEEK_DAY

SELECT CAL.YYMMDD
    , PRICE.*
    , EVN.EVN_PRICE * 1000
FROM M4S_I002030 CAL
JOIN (
        SELECT T1.PROJECT_CD
             , T1.ITEM_CD
             , T1.CON_PRICE
             , FORMAT(DATEADD(YEAR,8,T1.PRICE_START_YYMMDD),'yyyyMMdd') PRICE_START_YYMMDD
             , ISNULL(FORMAT(DATEADD(YEAR,8,T2.PRICE_START_YYMMDD),'yyyyMMdd'), FORMAT(CONVERT(DATE,'9999-12-31'),'yyyyMMdd')) PRICE_END_YYMMDD
        --     , CAL.*
        FROM M4S_I002041 T1
        LEFT OUTER JOIN M4S_I002041 T2
          ON 1=1
          AND T1.PROJECT_CD = T2.PROJECT_CD
          AND T1.ITEM_CD = T2.ITEM_CD
          AND T1.PRICE_QTY_UNIT_CD = T2.PRICE_QTY_UNIT_CD
          AND T1.PRICE_START_YYMMDD < T2.PRICE_START_YYMMDD
       WHERE 1=1
          AND T1.PROJECT_CD = 'ENT001'
          AND T1.PRICE_QTY_UNIT_CD = 'BOX'
          AND T1.ITEM_CD = '5107671'
    ) PRICE
  ON PRICE.PROJECT_CD = CAL.PROJECT_CD
  AND CAL.YYMMDD BETWEEN PRICE.PRICE_START_YYMMDD AND PRICE.PRICE_END_YYMMDD
LEFT JOIN M4S_I204100 EVN
ON CAL.YYMMDD BETWEEN DATEADD(DAY, -6, EVN.PLAN_FROM_YYMMDD) AND EVN.PLAN_TO_YYMMDD
AND PRICE.ITEM_CD = EVN.ITEM_CD
AND EVN.CUST_GRP_CD = '1095'
WHERE 1=1
  AND CAL.PROJECT_CD = 'ENT001'
  AND CAL.YY = '2021'
  AND CAL.YYMM = '202107'
  AND CAL.YYMMDD = CAL.START_WEEK_DAY
-- , (SELECT CAL.YYMMDD
--       ,CAL.WEEK
-- FROM M4S_I002030 CAL
-- WHERE CAL.PROJECT_CD = 'ENT001'
--   AND CAL.YY = '2021'
--   AND CAL.YYMMDD = CAL.START_WEEK_DAY) CAL
WHERE 1=1
  AND T1.PROJECT_CD = 'ENT001'
  AND T1.PRICE_QTY_UNIT_CD = 'BOX'
--   AND T1.ITEM_CD = '5100002'
--   AND T1.PRICE_START_YYMMDD <= CAL.YYMMDD


-- DELETE FROM M4S_I002060
WHERE PROJECT_CD IN (SELECT T1.PROJECT_CD
--     , T1.IF_VRSN_ID
--     , T1.CUST_CD
--     , T1.CUST_TYPE_CD
    --, MAX(T1.CUST_GRP_CD)
FROM M4S_I002060 T1
, M4S_I002060 T2
WHERE T1.PROJECT_CD = T2.PROJECT_CD
AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
AND T1.CUST_CD = T2.CUST_CD
AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
AND T1.CUST_GRP_CD != T2.CUST_GRP_CD
GROUP BY T1.PROJECT_CD
    , T1.IF_VRSN_ID
    , T1.CUST_CD
    , T1.CUST_TYPE_CD)
AND IF_VRSN_ID IN (SELECT  T1.IF_VRSN_ID
--     , T1.CUST_CD
--     , T1.CUST_TYPE_CD
    --, MAX(T1.CUST_GRP_CD)
FROM M4S_I002060 T1
, M4S_I002060 T2
WHERE T1.PROJECT_CD = T2.PROJECT_CD
AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
AND T1.CUST_CD = T2.CUST_CD
AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
AND T1.CUST_GRP_CD != T2.CUST_GRP_CD
GROUP BY T1.PROJECT_CD
    , T1.IF_VRSN_ID
    , T1.CUST_CD
    , T1.CUST_TYPE_CD)
AND CUST_CD IN (SELECT T1.CUST_CD
--     , T1.CUST_TYPE_CD
    --, MAX(T1.CUST_GRP_CD)
FROM M4S_I002060 T1
, M4S_I002060 T2
WHERE T1.PROJECT_CD = T2.PROJECT_CD
AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
AND T1.CUST_CD = T2.CUST_CD
AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
AND T1.CUST_GRP_CD != T2.CUST_GRP_CD
GROUP BY T1.PROJECT_CD
    , T1.IF_VRSN_ID
    , T1.CUST_CD
    , T1.CUST_TYPE_CD)
AND CUST_TYPE_CD IN (SELECT T1.CUST_TYPE_CD
    --, MAX(T1.CUST_GRP_CD)
FROM M4S_I002060 T1
, M4S_I002060 T2
WHERE T1.PROJECT_CD = T2.PROJECT_CD
AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
AND T1.CUST_CD = T2.CUST_CD
AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
AND T1.CUST_GRP_CD != T2.CUST_GRP_CD
GROUP BY T1.PROJECT_CD
    , T1.IF_VRSN_ID
    , T1.CUST_CD
    , T1.CUST_TYPE_CD)
-- AND CUST_GRP_CD NOT IN (SELECT MAX(T1.CUST_GRP_CD)
-- FROM M4S_I002060 T1
-- , M4S_I002060 T2
-- WHERE T1.PROJECT_CD = T2.PROJECT_CD
-- AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
-- AND T1.CUST_CD = T2.CUST_CD
-- AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
-- AND T1.CUST_GRP_CD != T2.CUST_GRP_CD
-- GROUP BY T1.PROJECT_CD
--     , T1.IF_VRSN_ID
--     , T1.CUST_CD
--     , T1.CUST_TYPE_CD)


SELECT T1.*
FROM M4S_I002060_1130_TMP T1
,(
SELECT T1.PROJECT_CD
    , T1.IF_VRSN_ID
    , T1.CUST_CD
    , T1.CUST_TYPE_CD
    , MAX(T1.CUST_GRP_CD) CUST_GRP_CD
FROM M4S_I002060 T1
, M4S_I002060 T2
WHERE T1.PROJECT_CD = T2.PROJECT_CD
AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
AND T1.CUST_CD = T2.CUST_CD
AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
AND T1.CUST_GRP_CD != T2.CUST_GRP_CD
GROUP BY T1.PROJECT_CD
    , T1.IF_VRSN_ID
    , T1.CUST_CD
    , T1.CUST_TYPE_CD) T2
WHERE T1.PROJECT_CD = T2.PROJECT_CD
AND T1.IF_VRSN_ID = T2.IF_VRSN_ID
AND T1.CUST_CD = T2.CUST_CD
AND T1.CUST_TYPE_CD = T2.CUST_TYPE_CD
AND T1.CUST_GRP_CD = T2.CUST_GRP_CD

SELECT * FROM M4S_I204020
WHERE SALES_MGMT_VRSN_ID = '202111_V0'
  and SALES_MGMT_TYPE_CD = 'SP1_C'
  AND LINK_SALES_MGMT_NM IN ('EC사업팀')
--AND LINK_SALES_MGMT_NM IN ('마켓컬리','쿠팡','배달의민족','이베이','디씽','푸드조이','기타')

SELECT * FROM M4S_I204030 T1
WHERE T1.SALES_MGMT_VRSN_ID = '202111_V0'
--   AND T1.SALES_MGMT_NM like '%EC사업팀%'
  AND SUBSTRING(T1.SALES_MGMT_CD,1,7) = 1420113
1219112
1420103  1420113

insert into M4S_I204040
SELECT *
FROM M4S_I204040
WHERE SALES_MGMT_VRSN_ID = '202111_V0'


INSERT INTO M4S_I204030
SELECT T1.PROJECT_CD
    , T1.SALES_MGMT_VRSN_ID
    , T1.SALES_MGMT_CD + T2.LINK_SALES_MGMT_CD
    , T2.LINK_SALES_MGMT_NM
    , T2.SALES_MGMT_TYPE_CD
    , T1.SALES_MGMT_CD
    , T2.LINK_SALES_MGMT_CD
    , NULL
    , NULL
    , 'Y'
    , 'N'
    , NULL
    , 'dev07'
    , getdate()
    , NULL
    , NULL
FROM M4S_I204030 T1
    , M4S_I204020 T2
WHERE T1.SALES_MGMT_VRSN_ID = '202111_V0'
  AND T1.SALES_MGMT_NM IN ('EC사업팀')
  AND SUBSTRING(T1.SALES_MGMT_CD,1,2) = 11
  AND T1.SALES_MGMT_TYPE_CD = 'SP1_C'
  AND T1.PROJECT_CD = T2.PROJECT_CD
  AND T1.SALES_MGMT_VRSN_ID = T2.SALES_MGMT_VRSN_ID
  AND T2.LINK_SALES_MGMT_NM IN ('쿠팡','이베이','마켓컬리','디씽','푸드조이','보담','기타')

-- insert into M4S_I204040
SELECT T2.PROJECT_CD
    , T2.SALES_MGMT_VRSN_ID
    , T2.SALES_MGMT_TYPE_CD
    , T2.SALES_MGMT_CD LINK_SALES_MGMT_CD
    , 'matrix'
    , 'dev07'
    , null
    , 'Y'
    , 'N'
    , 'dev07'
    , getdate()
    , null
    , null
FROM M4S_I204040 T1
    RIGHT OUTER JOIN M4S_I204030 T2
 ON 1=1
AND T1.PROJECT_CD = T2.PROJECT_CD
AND T1.SALES_MGMT_VRSN_ID = T2.SALES_MGMT_VRSN_ID
AND T1.SALES_MGMT_TYPE_CD = T2.SALES_MGMT_TYPE_CD
AND T1.LINK_SALES_MGMT_CD = T2.SALES_MGMT_CD
WHERE T2.PROJECT_CD = 'ENT001'
AND T2.SALES_MGMT_VRSN_ID = '202111_V0'
AND T1.PROJECT_CD IS NULL

SELECT * FROM M4S_I204040 WHERE SALES_MGMT_TYPE_CD NOT LIKE 'SP%'


SELECT FORMAT(CONVERT(DATE,EXG.YYMMDD),'yyyy-MM-dd') + ' (' + SUBSTRING(DATENAME(WEEKDAY, EXG.YYMMDD),1,1) + ')' YYMMDD
	, EXG.CURCY_CD
	, EXG.EXCHNG_RATE
    , CAL.YY
    , CAL.YYMM
    , CAL.WEEK
    , SUBSTRING(DATENAME(WEEKDAY, EXG.YYMMDD),1,1)
FROM M4S_I002140 EXG
 JOIN M4S_I002030 CAL
   ON EXG.PROJECT_CD = CAL.PROJECT_CD
  AND EXG.YYMMDD = CAL.YYMMDD
WHERE 1=1
  AND EXG.PROJECT_CD = :VS_P_PROJECT_CD



SELECT * FROM M4S_I204030
WHERE SALES_MGMT_VRSN_ID = '202111_V0'
  AND SUBSTRING(SALES_MGMT_CD,1,7) = '1219105'
  AND SALES_MGMT_NM NOT IN ('이마트','홈플러스','롯데슈퍼','GS유통','홈플러스슈퍼','이마트슈퍼','7-11','GS25','CU','미니스톱','이마트24')


SELECT T1.*
FROM M4S_I204030 T1
--  LEFT OUTER JOIN M4S_I204030 T2
-- ON T1.PROJECT_CD = T2.PROJECT_CD
--   AND T1.SALES_MGMT_VRSN_ID = T2.SALES_MGMT_VRSN_ID
--   AND T1.SALES_MGMT_TYPE_CD = T2.SALES_MGMT_TYPE_CD
--   AND T1.LINK_SALES_MGMT_CD = SUBSTRING(T2.SALES_MGMT_CD,8,4)
WHERE T1.SALES_MGMT_VRSN_ID = '202111_V0'
-- AND T2.PROJECT_CD IS NULL
AND T1.SALES_MGMT_TYPE_CD = 'SP1'


SELECT T1.* FROM M4S_I204050 T1
 LEFT OUTER JOIN M4S_I204030 T2
ON T1.PROJECT_CD = T2.PROJECT_CD
  AND T1.SALES_MGMT_VRSN_ID = T2.SALES_MGMT_VRSN_ID
  AND T1.SALES_MGMT_CD = T2.SALES_MGMT_CD
WHERE T1.SALES_MGMT_VRSN_ID = '202111_V0'
AND T2.PROJECT_CD IS NULL
  AND SUBSTRING(T1.SALES_MGMT_CD,1,7) = '1219105'
AND T2.SALES_MGMT_TYPE_CD = 'SP1'

