select * from m4s_i002171

SELECT ITEM.PROJECT_CD
     , ITEM.ITEM_CD
     , ITEM.ITEM_NM
     , ITEM.ITEM_TYPE_CD
     , ITEM.ITEM_GRP_CD
     , ITEM.ITEM_GRP_NM
     , ITEM.ITEM_CTGRI_CD
     , ITEM.ITEM_CTGRI_NM
     , ITEM.INF_ITEM_YN
     , ITEM.ITEM_ATTR01_CD
     , ITEM.ITEM_ATTR21_CD
     , ITEM.ITEM_ATTR02_CD
     , ITEM.ITEM_ATTR22_CD
     , ITEM.ITEM_ATTR03_CD
     , ITEM.ITEM_ATTR23_CD
     , ITEM.ITEM_ATTR04_CD
     , ITEM.ITEM_ATTR24_CD
     , ITEM.ITEM_ATTR05_CD
     , ITEM.ITEM_ATTR25_CD
     , ITEM.ITEM_ATTR06_CD
     , ITEM.ITEM_ATTR07_CD
     , ITEM.ITEM_ATTR08_CD
     , ITEM.ITEM_ATTR09_CD
     , ITEM.ITEM_ATTR10_CD
     , ITEM.ITEM_ATTR11_CD
     , ITEM.ITEM_ATTR12_CD
     , ITEM.ITEM_ATTR13_CD
     , ITEM.ITEM_ATTR14_CD
     , ITEM.ITEM_ATTR15_CD
     , ITEM.ITEM_ATTR16_CD
     , ITEM.ITEM_ATTR17_CD
     , ITEM.ITEM_ATTR18_CD
     , ITEM.ITEM_ATTR19_CD
     , ITEM.ITEM_ATTR20_CD
     , ITEM.LT_UNIT_CD
     , ITEM.MATERIAL_KEY_YN
     , ITEM.NEW_ITEM_YN
     , ITEM.NEW_ITEM_YYMMDD
     , ITEM.CREATE_USER_CD
     , ITEM.CREATE_DATE
     , ITEM.MODIFY_USER_CD
     , ITEM.MODIFY_DATE
FROM M4S_I002040 ITEM


SELECT *
FROM M4S_I204020
WHERE PROJECT_CD = :VS_P_PROJECT_CD
  AND SALES_MGMT_VRSN_ID = (SELECT SALES_MGMT_VRSN_ID FROM M4S_I204010 WHERE USE_YN = 'Y')
SELECT DISTINCT IDX_DTL_CD, IDX_DTL_NM FROM M4S_O110710


SELECT * INTO M4S_I002040_BAK_1222 FROM M4S_I002040

SELECT * FROM M4S_I001030 ORDER BY EXCUTE_DATE DESC


SELECT 'ENT001' AS PROJECT_CD
			 , RESULT.DATA_VRSN_CD
			 , RESULT.DIVISION_CD
			 , 'REVISION' AS CLASSIFY_CD
			 , 'REV' AS ITEM_TYPE_CD
			 , RESULT.STAT_CD
			 , RESULT.WEEK
			 , RESULT.YYMMDD
			 , SUM(RESULT.RESULT_SALES) * 70 / 100 AS RESULT_SALES
			 , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM
			 , 'dev07' AS CREATE_USER_CD
			 , GETDATE() AS CREATE_DATE
			 , 'dev07' AS MODIFY_USER_CD
			 , GETDATE() AS MODIFY_DATE
		 FROM M4S_O110600 RESULT
		    JOIN VIEW_I002040 ITEM
		      ON ITEM.ITEM_CD = '5141085'
		WHERE 1=1
		  AND RESULT.DATA_VRSN_CD = '20201102-20211031'
		  AND RESULT.DIVISION_CD = 'SELL_IN'
		  AND RESULT.FKEY LIKE '%C1-P5%'
		  AND RESULT.ITEM_CD = '5141087'
        GROUP BY RESULT.DATA_VRSN_CD
			 , RESULT.DIVISION_CD
			 , RESULT.STAT_CD
			 , RESULT.WEEK
			 , RESULT.YYMMDD
             , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM

SELECT 'ENT001' AS PROJECT_CD
     , FKEY
			 , RESULT.DATA_VRSN_CD
			 , RESULT.DIVISION_CD
			 , 'REVISION' AS CLASSIFY_CD
			 , 'REV' AS ITEM_TYPE_CD
			 , RESULT.STAT_CD
			 , RESULT.WEEK
			 , RESULT.YYMMDD
			 , RESULT.RESULT_SALES * 70 / 100 AS RESULT_SALES
			 , ITEM.ITEM_ATTR01_CD
			 , ITEM.ITEM_ATTR02_CD
			 , ITEM.ITEM_ATTR03_CD
			 , ITEM.ITEM_ATTR04_CD
			 , ITEM.ITEM_ATTR01_NM
			 , ITEM.ITEM_ATTR02_NM
			 , ITEM.ITEM_ATTR03_NM
			 , ITEM.ITEM_ATTR04_NM
			 , ITEM.ITEM_CD NEW_ITEM_CD
			 , ITEM.ITEM_CD
			 , ITEM.ITEM_NM
			 , 'dev07' AS CREATE_USER_CD
			 , GETDATE() AS CREATE_DATE
			 , 'dev07' AS MODIFY_USER_CD
			 , GETDATE() AS MODIFY_DATE
		 FROM M4S_O110600 RESULT
		    JOIN VIEW_I002040 ITEM
		      ON ITEM.ITEM_CD = '5141085'
		WHERE 1=1
		  AND RESULT.DATA_VRSN_CD = '20201102-20211031'
		  AND RESULT.DIVISION_CD = 'SELL_IN'
		  AND RESULT.FKEY LIKE '%C1-P5%'
		  AND RESULT.ITEM_CD = '5141087'