WITH  PT_NUM AS (


	SELECT START_PART_WEEK_DAY
		, ROW_NUMBER() OVER(ORDER BY START_PART_WEEK_DAY) AS RNT
	FROM M4S_I002030 T1
	WHERE 1=1
	 AND T1.YYMMDD BETWEEN '20211129' AND '20220306'

	GROUP BY START_PART_WEEK_DAY

)
, BEFORE_WEEK AS (

	SELECT T1.START_PART_WEEK_DAY AS A_WEEK
		,  T2.START_PART_WEEK_DAY AS B_WEEK
		,  T3.START_PART_WEEK_DAY AS C_WEEK
		,  T4.START_PART_WEEK_DAY AS D_WEEK
		,  T5.START_PART_WEEK_DAY AS E_WEEK
		,  T6.START_PART_WEEK_DAY AS F_WEEK
		,  T7.START_PART_WEEK_DAY AS G_WEEK
	FROM PT_NUM T1
		LEFT JOIN PT_NUM T2 ON ( T1.RNT = T2.RNT + 1 )
		LEFT JOIN PT_NUM T3 ON ( T1.RNT = T3.RNT - 1 )
		LEFT JOIN PT_NUM T4 ON ( T1.RNT = T4.RNT - 2 )
		LEFT JOIN PT_NUM T5 ON ( T1.RNT = T5.RNT - 3 )
		LEFT JOIN PT_NUM T6 ON ( T1.RNT = T6.RNT - 4 )
		LEFT JOIN PT_NUM T7 ON ( T1.RNT = T7.RNT - 5 )

)
, TB_SALES_CUST_ITEM AS (


		SELECT CUST.SALES_MGMT_CD
			 , CUST.SALES_MGMT_NM
			 , CUST.LINK_SALES_MGMT_CD
			 , CUST.CUST_CD
			 , CUST.CUST_NM
			 , SALES_ITEM.ITEM_CD
		FROM (
					SELECT TREE.SALES_MGMT_CD
						, TREE.SALES_MGMT_NM
						, TREE.LINK_SALES_MGMT_CD
						, CUST_SALES.CUST_CD
						, CUST_SALES.CUST_NM
					FROM  M4S_I204030  TREE
						  INNER JOIN (

										SELECT CUST_CD
											 , CUST_NM
											 , CUST_GRP_CD
										FROM M4S_I002060
										WHERE PROJECT_CD =  'ENT001'
										and USE_YN	 = 'Y'
										AND CUST_GRP_CD = '1068'

									) CUST_SALES ON ( TREE.LINK_SALES_MGMT_CD = CUST_SALES.CUST_GRP_CD )

					WHERE TREE.SALES_MGMT_VRSN_ID  = '202111_V0'
					AND TREE.SALES_MGMT_TYPE_CD = 'SP1'
					AND USE_YN = 'Y' ) CUST , (

													SELECT CUST.SALES_MGMT_CD
														 , CUST.ITEM_CD
													FROM M4S_I204050 CUST
													WHERE PROJECT_CD = 'ENT001'
													AND CUST.SALES_MGMT_VRSN_ID = '202111_V0'
													AND USER_CD = 'dev07'
													AND SUBSTRING(SALES_MGMT_CD,1,2) = SUBSTRING('11_1068',1,2)

												) SALES_ITEM
	WHERE CUST.SALES_MGMT_CD = SALES_ITEM.SALES_MGMT_CD
)


 SELECT PLAN_EDT.PROJECT_CD
	  , PLAN_EDT.DP_VRSN_ID
	  , PLAN_EDT.USER_CD
	  , PLAN_EDT.SALES_MGMT_CD
	  , PLAN_EDT.ITEM_CD
	  , PLAN_EDT.PLAN_YYMMDD
	  , PLAN_EDT.DP_QTY   AS SP1_M002
	  , PLAN_EDT.USER_CD
	  , '' AS SOLD_CUST_GRP_CD
	  , '' AS CUST_GRP_NM
	  , PLAN_EDT.MAIN_KEY
	  , ''					  AS CUST_ATTR02
	  , ''					  AS CUST_ATTR03
	  , ''					  AS CUST_ATTR04
	  , ''				  	  AS CUST_ATTR05
	  , PLAN_EDT.ITEM_NM
	  , PLAN_EDT.ITEM_ATTR01_CD
	  , PLAN_EDT.ITEM_ATTR01_NM AS ITEM_HIERARCHY_01
	  , PLAN_EDT.ITEM_ATTR02_CD
	  , PLAN_EDT.ITEM_ATTR02_NM AS ITEM_HIERARCHY_02
	  , PLAN_EDT.ITEM_ATTR03_CD
	  , PLAN_EDT.ITEM_ATTR03_NM AS ITEM_HIERARCHY_03
	  , PLAN_EDT.ITEM_ATTR04_CD
	  , PLAN_EDT.ITEM_ATTR04_NM AS ITEM_HIERARCHY_04
	  , PLAN_EDT.ITEM_ATTR05_CD
	  , PLAN_EDT.YYMMDD
	  , PLAN_EDT.PLAN_YYMM
	  , PLAN_EDT.PLAN_YY
	  , PLAN_EDT.PLAN_PART_WEEK
	  , PLAN_EDT.PLAN_WEEK
	  , 0 CON_PRICE
	  , 0 FAC_PRICE
	  , ISNULL(PRICE.SHP_PRICE,0) SP1_M014
	  , 0 AGN_PRICE
	  , ISNULL(PRICE.COT_PRICE,0)  AS SP1_M008
      , EVN.EVN_PRICE
	  , ISNULL(EVN.EVN_PRICE * 1000, ISNULL(PRICE.COT_PRICE,0)) END AS SP1_M009
-- 	  , 0					  AS SP1_M010
-- 	  , ISNULL(RST.RST_QTY,0) AS SP1_M011
-- 	  , ISNULL(RST_OUT.RST_QTY,0)	  AS SP1_M012
-- 	  , ISNULL(FCST.RESULT_SALES,0)	  AS SP1_M006
-- 	  , ISNULL(FCST_OUT.RESULT_SALES, 0)	AS SP1_M007
-- 	  , 0				AS SP1_M013
-- 	  , 0				AS SP1_M003
-- 	  , 0				AS SP1_M004
-- 	  , 0				AS SP1_M005
-- 	  , 0				AS SP1_M015
-- 	  , CONVERT(DATE, B_WEEK.B_WEEK)   AS ATTR14
-- 	  , CONVERT(DATE, B_WEEK.C_WEEK)   AS ATTR15
-- 	  , CONVERT(DATE, B_WEEK.D_WEEK)   AS ATTR16
-- 	  , CONVERT(DATE, B_WEEK.E_WEEK)   AS ATTR17
-- 	  , CONVERT(DATE, B_WEEK.F_WEEK)   AS ATTR18
-- 	  , CONVERT(DATE, B_WEEK.G_WEEK)   AS ATTR19
-- 	  , ''				AS FUNC01
-- 	  , ''				AS FUNC02
-- 	  , ''				AS FUNC03
-- 	  , ''				AS FUNC04
-- 	  , ''				AS FUNC05
-- 	  , ''				AS FUNC06
-- 	  , ''				AS FUNC07
-- 	  , ''				AS FUNC08
-- 	  , ''				AS FUNC09
-- 	  , ''				AS FUNC10
 FROM (

		 SELECT T1.PROJECT_CD
			  , T1.DP_VRSN_ID
			  , T1.SALES_MGMT_CD
			  , T1.ITEM_CD
			  , T1.PLAN_YYMMDD
			  , CONVERT(VARCHAR(10),DATEADD(DAY,0,PLAN_YYMMDD),121) AS YYMMDD
			  , T1.USER_CD
			  , T1.SALES_MGMT_CD + '_' + T1.ITEM_CD + '_' +PLAN_YYMMDD AS MAIN_KEY
			  , T1.PLAN_WEEK
			  , T1.PLAN_PART_WEEK
			  , T1.PLAN_YYMM
			  , T1.PLAN_YY
              , T2.ITEM_NM
			  , T2.ITEM_ATTR01_CD
			  , T2.ITEM_ATTR01_NM
			  , T2.ITEM_ATTR02_CD
			  , T2.ITEM_ATTR02_NM
			  , T2.ITEM_ATTR03_CD
			  , T2.ITEM_ATTR03_NM
			  , T2.ITEM_ATTR04_CD
			  , T2.ITEM_ATTR04_NM
			  , T2.ITEM_ATTR05_CD
              , T2.UNIT_CD
			  , SUM(DP_QTY) AS DP_QTY
		 FROM  M4S_O201001 T1
              INNER JOIN VIEW_I002040 T2
		      ON 1=1
		      AND PROJECT_CD = 'ENT001'
		      AND DP_VRSN_ID = 'SP_2021W49.01'
		      AND SUBSTRING(SALES_MGMT_CD,1,2) =  SUBSTRING('11_1068',1,2)
			  AND SUBSTRING(SALES_MGMT_CD,8,4) = '1068'
		      AND USER_CD = 'dev07'
              AND T1.ITEM_CD = T2.ITEM_CD
		 GROUP BY T1.PROJECT_CD
			    , T1.DP_VRSN_ID
			    , T1.SALES_MGMT_CD
			    , T1.ITEM_CD
			    , T1.PLAN_YYMMDD
			    , T1.USER_CD
			    , T1.PLAN_WEEK
			    , T1.PLAN_PART_WEEK
			    , T1.PLAN_YYMM
			    , T1.PLAN_YY
                , T2.ITEM_NM
			  , T2.ITEM_ATTR01_CD
			  , T2.ITEM_ATTR01_NM
			  , T2.ITEM_ATTR02_CD
			  , T2.ITEM_ATTR02_NM
			  , T2.ITEM_ATTR03_CD
			  , T2.ITEM_ATTR03_NM
			  , T2.ITEM_ATTR04_CD
			  , T2.ITEM_ATTR04_NM
			  , T2.ITEM_ATTR05_CD
              , T2.UNIT_CD         ) PLAN_EDT
     LEFT HASH JOIN (  SELECT ITEM_CD
	  		           , PRICE_QTY_UNIT_CD
	  		           , SHP_PRICE
					   , COT_PRICE
	  	            FROM M4S_I002041
	  	           WHERE PROJECT_CD = 'ENT001'

				   ) PRICE
     ON PLAN_EDT.ITEM_CD = PRICE.ITEM_CD
	 AND ISNULL(PLAN_EDT.UNIT_CD,'') = PRICE.PRICE_QTY_UNIT_CD

    LEFT OUTER JOIN TMP_M4S_I204100 EVN
    ON PLAN_EDT.YYMMDD BETWEEN DATEADD(DAY, -6, EVN.PLAN_FROM_YYMMDD) AND EVN.PLAN_TO_YYMMDD
     AND PLAN_EDT.ITEM_CD = EVN.ITEM_CD
     AND SUBSTRING(PLAN_EDT.SALES_MGMT_CD,8,4) = EVN.CUST_GRP_CD
--
-- 	LEFT HASH JOIN (
--
--
--
-- 			SELECT FCST.YYMMDD
-- 				, FCST.WEEK
-- 				, FCST.CUST_GRP_CD
--                 , SC.SALES_MGMT_CD
-- 				, FCST.ITEM_CD
-- 				, SUM( FCST.RESULT_SALES ) AS RESULT_SALES
-- 			FROM M4S_O110600  FCST
-- 			     INNER HASH JOIN (SELECT LINK_SALES_MGMT_CD
--                                         ,ITEM_CD
--                                         ,SALES_MGMT_CD
--                                     FROM TB_SALES_CUST_ITEM
--                                    GROUP BY LINK_SALES_MGMT_CD
--                                         ,ITEM_CD
--                                         ,SALES_MGMT_CD )SC
-- 			     ON FCST.CUST_GRP_CD = SC.LINK_SALES_MGMT_CD
-- 				AND FCST.ITEM_CD = SC.ITEM_CD
-- 		  WHERE FCST.PROJECT_CD   = 'ENT001'
-- 			AND FCST.DIVISION_CD = 'SELL_IN'
-- 			AND FKEY LIKE '%C1%'
-- 			GROUP BY FCST.YYMMDD
-- 				, FCST.WEEK
-- 				, FCST.CUST_GRP_CD
--                 , SC.SALES_MGMT_CD
-- 				, FCST.ITEM_CD
--
--
-- 	) FCST ON ( PLAN_EDT.PLAN_WEEK = FCST.WEEK
-- 			AND PLAN_EDT.PLAN_YYMMDD = FCST.YYMMDD
-- 			AND PLAN_EDT.ITEM_CD = FCST.ITEM_CD
--             AND PLAN_EDT.SALES_MGMT_CD = FCST.SALES_MGMT_CD
-- 			 )
--
-- 	LEFT HASH JOIN (
--
--
--
-- 			SELECT FCST.YYMMDD
-- 				, FCST.WEEK
-- 				, FCST.CUST_GRP_CD
--                 , SC.SALES_MGMT_CD
-- 				, FCST.ITEM_CD
-- 				, SUM( FCST.RESULT_SALES ) AS RESULT_SALES
-- 			FROM M4S_O110600  FCST
-- 			     INNER HASH JOIN (SELECT LINK_SALES_MGMT_CD
--                                         ,ITEM_CD
--                                         ,SALES_MGMT_CD
--                                     FROM TB_SALES_CUST_ITEM
--                                    GROUP BY LINK_SALES_MGMT_CD
--                                         ,ITEM_CD
--                                         ,SALES_MGMT_CD )SC
-- 			     ON FCST.CUST_GRP_CD = SC.LINK_SALES_MGMT_CD
-- 				AND FCST.ITEM_CD = SC.ITEM_CD
--
-- 		  WHERE FCST.PROJECT_CD   = 'ENT001'
-- 		    AND FCST.DIVISION_CD = 'SELL_OUT'
-- 			AND FKEY LIKE '%C1%'
-- 			GROUP BY FCST.YYMMDD
-- 				, FCST.WEEK
-- 				, FCST.CUST_GRP_CD
--                 , SC.SALES_MGMT_CD
-- 				, FCST.ITEM_CD
--
--
-- 	) FCST_OUT ON ( PLAN_EDT.PLAN_WEEK = FCST_OUT.WEEK
-- 			AND PLAN_EDT.PLAN_YYMMDD = FCST_OUT.YYMMDD
-- 			AND PLAN_EDT.ITEM_CD = FCST_OUT.ITEM_CD
--             AND PLAN_EDT.SALES_MGMT_CD = FCST_OUT.SALES_MGMT_CD
-- 			 )
--
-- 	LEFT HASH JOIN (
--
--
-- 		SELECT SELLIN.ITEM_CD
--             , SC.SALES_MGMT_CD
-- 			, WEEK
-- 			, PART_WEEK
-- 			, SUM(RST_SALES_QTY) AS RST_QTY
-- 		FROM M4S_I002170  SELLIN
-- 		     INNER HASH JOIN TB_SALES_CUST_ITEM SC
-- 		  ON PROJECT_CD = 'ENT001'
-- 		 AND YY = '2020'
--
-- 		 AND YYMM BETWEEN '202011' AND '202103'
-- 		 AND SELLIN.SOLD_CUST_GRP_CD = SC.CUST_CD
-- 		 AND SELLIN.ITEM_CD = SC.ITEM_CD
-- 		 GROUP BY SELLIN.ITEM_CD
--                , SC.SALES_MGMT_CD
-- 		  	   , WEEK
-- 			   , PART_WEEK
--
--
-- 	) RST ON ( PLAN_EDT.PLAN_WEEK = RST.WEEK
-- 			 AND PLAN_EDT.PLAN_PART_WEEK = RST.PART_WEEK
-- 			 AND PLAN_EDT.ITEM_CD = RST.ITEM_CD
--              AND PLAN_EDT.SALES_MGMT_CD = RST.SALES_MGMT_CD
-- 			 )
--
-- 	LEFT HASH JOIN (
--
--
-- 		SELECT SELLOUT.ITEM_CD
--             , SC.SALES_MGMT_CD
-- 			, WEEK
-- 			, PART_WEEK
-- 			, SUM(RST_SALES_QTY) AS RST_QTY
-- 		FROM M4S_I002173  SELLOUT
-- 		     INNER HASH JOIN TB_SALES_CUST_ITEM SC
-- 		  ON PROJECT_CD = 'ENT001'
-- 		 AND YY = '2020'
--
-- 		 AND YYMM BETWEEN '202011' AND '202103'
-- 		 AND SELLOUT.SOLD_CUST_GRP_CD = SC.LINK_SALES_MGMT_CD
-- 		 AND SELLOUT.ITEM_CD = SC.ITEM_CD
-- 		 GROUP BY SELLOUT.ITEM_CD
--                , SC.SALES_MGMT_CD
-- 		  	   , WEEK
-- 			   , PART_WEEK
--
--
-- 	) RST_OUT ON ( PLAN_EDT.PLAN_WEEK = RST_OUT.WEEK
-- 			 AND PLAN_EDT.PLAN_PART_WEEK = RST_OUT.PART_WEEK
-- 			 AND PLAN_EDT.ITEM_CD = RST_OUT.ITEM_CD
--              AND PLAN_EDT.SALES_MGMT_CD = RST_OUT.SALES_MGMT_CD
-- 			 )
--
-- 	LEFT  JOIN BEFORE_WEEK B_WEEK ON (PLAN_EDT.PLAN_YYMMDD = B_WEEK.A_WEEK)
 ORDER BY PLAN_EDT.SALES_MGMT_CD
		, PLAN_EDT.YYMMDD