create  OR ALTER procedure dbo.PRC_SALES_MATRIX_MAPPING
(
    @V_PROJECT_CD VARCHAR(50),
    @V_SALES_MGMT_VRSN_ID VARCHAR(20)
)
AS
BEGIN
DECLARE @V_PROC_NM VARCHAR(50)

SET NOCOUNT ON;

    SET @V_PROC_NM = 'PRC_SALES_MATRIX_MAPPING'
    exec dbo.MTX_SCM_PROC_LOG @V_PROJECT_CD, @V_PROC_NM, 'PRC_DF_NPI_REVISION 프로시저', 'ALL START';

    DELETE FROM M4S_I204050
    WHERE PROJECT_CD = @V_PROJECT_CD
      AND SALES_MGMT_VRSN_ID = @V_SALES_MGMT_VRSN_ID
    ;
    --01.START--
    exec dbo.MTX_SCM_PROC_LOG @V_PROJECT_CD, @V_PROC_NM,'(1) START', '01.START';

    -- 직전 3달 실적이 존재하는 CUST_GRP - ITEM 자동으로 새로운 영업관리 버전에 연결
    INSERT INTO M4S_I204050
    SELECT SMC.PROJECT_CD
    , @V_SALES_MGMT_VRSN_ID
    , SMC.SALES_MGMT_CD
    , SMC.ITEM_CD
    , SMC.USER_CD
    , 'N'
    , 'Y'
    , NULL
    , 'SYSTEM'
    , GETDATE()
    , NULL
    , NULL
    FROM M4S_I204050 SMC
    JOIN (
        SELECT CUST.PROJECT_CD
             , CUST.CUST_GRP_CD
             , RST.ITEM_CD
        FROM M4S_I002060 CUST
                 JOIN (SELECT PROJECT_CD
                            , SOLD_CUST_GRP_CD
                            , ITEM_CD
                       FROM M4S_I002170
                       WHERE PROJECT_CD = @V_PROJECT_CD
                         AND DIVISION_CD = 'SELL_IN'
                         AND YYMMDD BETWEEN DATEADD(MM, DATEDIFF(MM, 0, DATEADD(MONTH, -3, CONVERT(DATE, SUBSTRING(@V_SALES_MGMT_VRSN_ID, 1, 6) + '01'))),0) AND DATEADD(MM, DATEDIFF(MM, 0, CONVERT(DATE, SUBSTRING(@V_SALES_MGMT_VRSN_ID, 1, 6) + '01')), 0)
                       GROUP BY PROJECT_CD
                              , SOLD_CUST_GRP_CD
                              , ITEM_CD) RST
                      ON CUST.PROJECT_CD = RST.PROJECT_CD
                          AND CUST.CUST_CD = RST.SOLD_CUST_GRP_CD
    ) RST
    ON SMC.PROJECT_CD = RST.PROJECT_CD
    AND SUBSTRING(SMC.SALES_MGMT_CD,8,4) = RST.CUST_GRP_CD
    AND SMC.ITEM_CD = RST.ITEM_CD
    WHERE 1=1
      AND SMC.PROJECT_CD = @V_PROJECT_CD
      AND SMC.SALES_MGMT_VRSN_ID = '202111_V0'--FORMAT(DATEADD(MONTH, -1, CONVERT(DATE, SUBSTRING(@V_SALES_MGMT_VRSN_ID, 1, 6) + '01')),'yyyyMM') + '_V0'
    ;

    SELECT SMC.PROJECT_CD
    , @V_SALES_MGMT_VRSN_ID
    , SMC.SALES_MGMT_CD
    , SMC.ITEM_CD
    , SMC.USER_CD
    , 'N'
    , 'Y'
    , NULL
    , 'SYSTEM'
    , GETDATE()
    , NULL
    , NULL
    FROM M4S_I204050 SMC
    JOIN (
        SELECT CUST.PROJECT_CD
             , CUST.CUST_GRP_CD
             , RST.ITEM_CD
        FROM M4S_I002060 CUST
                 JOIN (SELECT PROJECT_CD
                            , SOLD_CUST_GRP_CD
                            , ITEM_CD
                       FROM M4S_I002170
                       WHERE PROJECT_CD = @V_PROJECT_CD
                         AND DIVISION_CD = 'SELL_IN'
                         AND YYMMDD BETWEEN DATEADD(MM, DATEDIFF(MM, 0, DATEADD(MONTH, -3, CONVERT(DATE, SUBSTRING(@V_SALES_MGMT_VRSN_ID, 1, 6) + '01'))),0) AND DATEADD(MM, DATEDIFF(MM, 0, CONVERT(DATE, SUBSTRING(@V_SALES_MGMT_VRSN_ID, 1, 6) + '01')), 0)
                       GROUP BY PROJECT_CD
                              , SOLD_CUST_GRP_CD
                              , ITEM_CD) RST
                      ON CUST.PROJECT_CD = RST.PROJECT_CD
                          AND CUST.CUST_CD = RST.SOLD_CUST_GRP_CD
    ) RST
    ON SMC.PROJECT_CD = RST.PROJECT_CD
    AND SUBSTRING(SMC.SALES_MGMT_CD,8,4) = RST.CUST_GRP_CD
    AND SMC.ITEM_CD = RST.ITEM_CD
    WHERE 1=1
      AND SMC.PROJECT_CD = @V_PROJECT_CD
      AND SMC.SALES_MGMT_VRSN_ID = '202111_V0'--FORMAT(DATEADD(MONTH, -1, CONVERT(DATE, SUBSTRING(@V_SALES_MGMT_VRSN_ID, 1, 6) + '01')),'yyyyMM') + '_V0'
    ;


    exec dbo.MTX_SCM_PROC_LOG @V_PROJECT_CD, @V_PROC_NM,'(1) END', '01.END';

    DECLARE @ERRM VARCHAR(200)

	SET @ERRM = ERROR_MESSAGE()
    exec dbo.MTX_SCM_PROC_LOG @V_PROJECT_CD, @V_PROC_NM, @ERRM, 'ALL END';
end
