SELECT PROJECT_CD
      ,YYMM
      ,SP1_CD
      ,LV_1_CD
      ,'' AS LV_2_CD
      ,'' AS LV_2_NM
      ,SUM(DAY_01) AS DAY_01
      ,SUM(DAY_02) AS DAY_02
      ,SUM(DAY_03) AS DAY_03
      ,SUM(DAY_04) AS DAY_04
      ,SUM(DAY_05) AS DAY_05
      ,SUM(DAY_06) AS DAY_06
      ,SUM(DAY_07) AS DAY_07
      ,SUM(DAY_08) AS DAY_08
      ,SUM(DAY_09) AS DAY_09
      ,SUM(DAY_10) AS DAY_10
      ,SUM(DAY_11) AS DAY_11
      ,SUM(DAY_12) AS DAY_12
      ,SUM(DAY_13) AS DAY_13
      ,SUM(DAY_14) AS DAY_14
      ,SUM(DAY_15) AS DAY_15
      ,SUM(DAY_16) AS DAY_16
      ,SUM(DAY_17) AS DAY_17
      ,SUM(DAY_18) AS DAY_18
      ,SUM(DAY_19) AS DAY_19
      ,SUM(DAY_20) AS DAY_20
      ,SUM(DAY_21) AS DAY_21
      ,SUM(DAY_22) AS DAY_22
      ,SUM(DAY_23) AS DAY_23
      ,SUM(DAY_24) AS DAY_24
      ,SUM(DAY_25) AS DAY_25
      ,SUM(DAY_26) AS DAY_26
      ,SUM(DAY_27) AS DAY_27
      ,SUM(DAY_28) AS DAY_28
      ,SUM(DAY_29) AS DAY_29
      ,SUM(DAY_30) AS DAY_30
      ,SUM(DAY_31) AS DAY_31
  FROM M4S_I002271
 WHERE YYMM       IN ( :VN_INSUM ) ---전월 1년전월 합
   AND LV_1_CD    = 'LINE'
   AND SP1_CD     = :VS_SELECT
   AND PROJECT_CD = :VS_PROJECT_CD
 GROUP BY PROJECT_CD
         ,YYMM
         ,SP1_CD
         ,LV_1_CD
UNION ALL
SELECT SELL_OUT.PROJECT_CD
      ,SELL_OUT.YYMM
      ,SELL_OUT.SP1_CD
      ,'라인' AS LV_1_CD  --SELL_OUT.LV_1_CD
      ,SELL_OUT.LV_2_CD
      ,SELL_OUT.LV_2_NM
      ,SELL_OUT.DAY_01
      ,SELL_OUT.DAY_02
      ,SELL_OUT.DAY_03
      ,SELL_OUT.DAY_04
      ,SELL_OUT.DAY_05
      ,SELL_OUT.DAY_06
      ,SELL_OUT.DAY_07
      ,SELL_OUT.DAY_08
      ,SELL_OUT.DAY_09
      ,SELL_OUT.DAY_10
      ,SELL_OUT.DAY_11
      ,SELL_OUT.DAY_12
      ,SELL_OUT.DAY_13
      ,SELL_OUT.DAY_14
      ,SELL_OUT.DAY_15
      ,SELL_OUT.DAY_16
      ,SELL_OUT.DAY_17
      ,SELL_OUT.DAY_18
      ,SELL_OUT.DAY_19
      ,SELL_OUT.DAY_20
      ,SELL_OUT.DAY_21
      ,SELL_OUT.DAY_22
      ,SELL_OUT.DAY_23
      ,SELL_OUT.DAY_24
      ,SELL_OUT.DAY_25
      ,SELL_OUT.DAY_26
      ,SELL_OUT.DAY_27
      ,SELL_OUT.DAY_28
      ,SELL_OUT.DAY_29
      ,SELL_OUT.DAY_30
      ,SELL_OUT.DAY_31
  FROM M4S_I002271 SELL_OUT
 WHERE SELL_OUT.YYMM       = :VS_YYMM ---선택월
   AND SELL_OUT.LV_1_CD    = 'LINE'
   AND SELL_OUT.SP1_CD     = :VS_SELECT ---
   AND SELL_OUT.PROJECT_CD = :VS_PROJECT_CD

UNION ALL

SELECT SELL_OUT.PROJECT_CD
      ,SELL_OUT.YYMM
      ,SELL_OUT.SP1_CD
      ,COMM.COMM_DTL_CD_NM
      ,SELL_OUT.LV_2_CD
      ,SELL_OUT.LV_2_NM
      ,SELL_OUT.DAY_01
      ,SELL_OUT.DAY_02
      ,SELL_OUT.DAY_03
      ,SELL_OUT.DAY_04
      ,SELL_OUT.DAY_05
      ,SELL_OUT.DAY_06
      ,SELL_OUT.DAY_07
      ,SELL_OUT.DAY_08
      ,SELL_OUT.DAY_09
      ,SELL_OUT.DAY_10
      ,SELL_OUT.DAY_11
      ,SELL_OUT.DAY_12
      ,SELL_OUT.DAY_13
      ,SELL_OUT.DAY_14
      ,SELL_OUT.DAY_15
      ,SELL_OUT.DAY_16
      ,SELL_OUT.DAY_17
      ,SELL_OUT.DAY_18
      ,SELL_OUT.DAY_19
      ,SELL_OUT.DAY_20
      ,SELL_OUT.DAY_21
      ,SELL_OUT.DAY_22
      ,SELL_OUT.DAY_23
      ,SELL_OUT.DAY_24
      ,SELL_OUT.DAY_25
      ,SELL_OUT.DAY_26
      ,SELL_OUT.DAY_27
      ,SELL_OUT.DAY_28
      ,SELL_OUT.DAY_29
      ,SELL_OUT.DAY_30
      ,SELL_OUT.DAY_31
  FROM M4S_I002271 SELL_OUT
    JOIN M4S_I204023 ISSUE_BRAND
      ON SELL_OUT.PROJECT_CD = ISSUE_BRAND.PROJECT_CD
     AND SELL_OUT.SP1_CD = ISSUE_BRAND.SALES_MGMT_CD
     AND SELL_OUT.YYMM = ISSUE_BRAND.YYMM
     AND SELL_OUT.LV_1_CD = ISSUE_BRAND.DIVISION_CD
     AND SELL_OUT.LV_2_CD = ISSUE_BRAND.ISSUE_CD
    JOIN M4S_I002011 COMM
      ON SELL_OUT.PROJECT_CD = COMM.PROJECT_CD
     AND SELL_OUT.LV_1_CD = COMM.COMM_DTL_CD
     AND COMM.COMM_CD = 'DF_LEVEL'
 WHERE SELL_OUT.YYMM       IN (:VN_YYMM) ---선택월
   AND SELL_OUT.LV_1_CD    <> 'LINE'
   AND SELL_OUT.SP1_CD     = :VS_SELECT ---
   AND SELL_OUT.PROJECT_CD = :VS_PROJECT_CD


SELECT * FROM M4S_O201010

UPDATE M4S_O201010 SET SP1_YN = 'Y' WHERE DP_VRSN_ID = 'SP_2022W02.01'

SP_2022W02.01
SELECT SP1_YN
    , SP2_YN
FROM M4S_O201010
WHERE 1=1
  AND PROJECT_CD = :VS_PROJECT_CD
  AND DP_VRSN_ID = :VS_CB_DP_VRSN_ID


SELECT * FROM M4S_I002271

SELECT ITEM.ITEM_CD
	 , ITEM.ITEM_NM
	 , ITEM.ITEM_ATTR01_CD
	 , ITEM.ITEM_ATTR02_CD
	 , ITEM.ITEM_ATTR03_CD
	 , ITEM.ITEM_ATTR04_CD
	 , ITEM.ITEM_ATTR01_NM
	 , ITEM.ITEM_ATTR02_NM
	 , ITEM.ITEM_ATTR03_NM
	 , ITEM.ITEM_ATTR04_NM
FROM VIEW_I002040 ITEM
WHERE 1=1
  AND ITEM.ITEM_ATTR01_CD IN (:VS_CB_BIZ_CD)
  AND ITEM.ITEM_ATTR02_CD IN (:VS_CB_LINE_CD)
  AND ITEM.ITEM_ATTR03_CD IN (:VS_CB_BRAND_CD)
  AND ITEM.ITEM_TYPE_CD = 'FERT'
  AND ITEM.USE_YN 		= 'Y'
ORDER BY ITEM.ITEM_CD
