SELECT T1.ITEM_CD
	  ,T1.ITEM_NM
	  ,T1.ITEM_TYPE_CD ITEM_TYPE_CD_CD
	  --,T10.COMM_DTL_CD_NM ITEM_TYPE_CD
  	  ,T1.ITEM_GRP_CD
  	  ,T1.ITEM_GRP_NM	  
	  ,T1.ITEM_CTGRI_CD
	  ,T1.ITEM_CTGRI_NM
	  ,T1.INF_ITEM_YN
      ,T1.DF_ITEM_CD
      ,T1.PKG_CD
      ,T1.UNIT_CD
      ,T1.DOME_CD
      ,T1.PROD_STRA_CD
      ,T1.PROD_STRA_SUB_CD
	  ,T1.ITEM_STRA_CD
	  ,T1.ITEM_GRADE
      ,T1.PKG_CTGRI_CD
      ,T1.PKG_CTGRI_SUB_CD	  
	  ,T1.PROD_ORDER_CD
	  ,T1.MILEAGE_CD
	  ,T1.DESCR
	  ,CASE WHEN T1.USE_YN = '' THEN 'Y'
	        WHEN T1.USE_YN IS NULL THEN 'Y'
			ELSE T1.USE_YN END AS USE_YN
	  ,CASE WHEN T1.DEL_YN = '' THEN 'Y'
	        WHEN T1.DEL_YN IS NULL THEN 'Y'
			ELSE T1.DEL_YN END AS DEL_YN
	  ,T1.ITEM_ATTR01_NM ITEM_ATTR01_CD-- T1.ITEM_ATTR01_CD
	  ,T1.ITEM_ATTR02_NM ITEM_ATTR02_CD-- T1.ITEM_ATTR02_CD
	  ,T1.ITEM_ATTR03_NM ITEM_ATTR03_CD-- T1.ITEM_ATTR03_CD
	  ,T1.ITEM_ATTR04_NM ITEM_ATTR04_CD-- T1.ITEM_ATTR04_CD
	  ,T1.ITEM_ATTR01_CD ITEM_ATTR01_CD_CD
	  ,T1.ITEM_ATTR02_CD ITEM_ATTR02_CD_CD
	  ,T1.ITEM_ATTR03_CD ITEM_ATTR03_CD_CD
	  ,T1.ITEM_ATTR04_CD ITEM_ATTR04_CD_CD
	  ,T1.ITEM_ATTR06_CD
	  ,T1.ITEM_ATTR07_CD
	  ,T1.ITEM_ATTR08_CD
	  ,T1.ITEM_ATTR09_CD
	  ,T1.ITEM_ATTR10_CD
	  
	  ,T1.ITEM_ATTR11_CD
	  ,T1.ITEM_ATTR12_CD
	  ,T1.ITEM_ATTR13_CD
	  ,T1.ITEM_ATTR14_CD
	  ,T1.ITEM_ATTR15_CD
	  ,T1.ITEM_ATTR16_CD
	  ,T1.ITEM_ATTR17_CD
	  ,T1.ITEM_ATTR18_CD
	  ,T1.ITEM_ATTR19_CD
	  ,T1.ITEM_ATTR20_CD
	  ,T1.ITEM_ATTR21_CD
	  ,T1.ITEM_ATTR22_CD
	  ,T1.ITEM_ATTR23_CD
	  ,T1.ITEM_ATTR24_CD
	  ,T1.ITEM_ATTR25_CD
	  ,T1.ITEM_ATTR26_CD
	  ,T1.ITEM_ATTR27_CD
	  ,T1.ITEM_ATTR28_CD
	  ,T1.ITEM_ATTR29_CD
	  ,T1.ITEM_ATTR30_CD
	  ,T1.AGING_PERIOD
  FROM VIEW_I002040 T1 --MTX_SCM_CM_M0030 T1 