SELECT * FROM TMP_M4S_O201001_1206

SELECT * FROM M4S_O201002 WHERE SUBSTRING(SALES_MGMT_CD,1,2) = '11' AND SUBSTRING(SALES_MGMT_CD,5,3) = '102'  ORDER BY CREATE_DATE DESC


SELECT COUNT(*)
        FROM M4S_O201002
        WHERE 1=1
           AND PROJECT_CD = 'ENT001'
           AND DP_VRSN_ID = 'SP_2021W49.01'
           AND SUBSTRING(SALES_MGMT_CD,1,2) = '11'
           AND SUBSTRING(SALES_MGMT_CD,5,3) = '102'
        ;

SELECT * FROM M4S_I001030 ORDER BY EXCUTE_DATE DESC


SELECT * FROM M4S_I002011
WHERE COMM_CD = 'SP_HORIZON_CD'
	   AND COMM_DTL_CD = 'HORIZON_CD'

SELECT DATEADD(WEEK, 3, '20211129')




    SELECT MT.PROJECT_CD
          ,'SP_2021W49.01'    AS DP_VRSN_ID
          ,MT.SALES_MGMT_CD
          ,MT.ITEM_CD
          ,MT.USER_CD
          ,T1.YYMMDD
          ,T1.WEEK
          ,T1.PART_WEEK
          ,T1.YYMM
          ,T1.YY
          ,0                AS DP_QTY
          ,'dev07'       AS CREATE_USER_CD
          ,GETDATE()        AS CREATE_DATE
      FROM M4S_I204050 MT
          ,(SELECT CAL.START_PART_WEEK_DAY AS YYMMDD
				  ,CAL.WEEK
				  ,CAL.PART_WEEK
				  ,CAL.YYMM
				  ,CAL.YY
			  FROM M4S_I002030 CAL
			 WHERE YYMMDD BETWEEN '20211129' AND FORMAT(DATEADD(WEEK, 3, '20211129'),'yyyyMMdd')
-- 			 WHERE YYMM >= '20211129'
--                AND YYMM <= CASE WHEN @WEEK_CNT <= 2 THEN CONVERT(VARCHAR(6),DATEADD(MONTH,1,'20211129'),112)
--                                 ELSE CONVERT(VARCHAR(6),DATEADD(MONTH,0,'20211129'),112) END
		  GROUP BY CAL.START_PART_WEEK_DAY
				  ,CAL.WEEK
				  ,CAL.PART_WEEK
				  ,CAL.YYMM
				  ,CAL.YY
--              UNION
--             SELECT CAL.YYMMDD
-- 				  ,CAL.WEEK
-- 				  ,CAL.PART_WEEK
-- 				  ,CAL.YYMM
-- 				  ,CAL.YY
-- 			  FROM M4S_I002030 CAL
--                   ,(
--                       SELECT CAL.START_MONTH_DAY AS YYMMDD
--                           FROM M4S_I002030 CAL
--                          WHERE YYMM > SUBSTRING('20211129',1,6)
--                            AND YYMM <= CASE WHEN @WEEK_CNT <= 2 THEN CONVERT(VARCHAR(6),DATEADD(MONTH,3,'20211129'),112)
--                                             ELSE CONVERT(VARCHAR(6),DATEADD(MONTH,2,'20211129'),112) END
--                       GROUP BY CAL.START_MONTH_DAY
--                     ) T2
-- 			 WHERE CAL.YYMMDD = T2.YYMMDD
		  ) T1
     WHERE 1=1
       AND PROJECT_CD     = 'ENT001'
       AND SALES_MGMT_VRSN_ID   = '202111_V0'
       AND DEL_YN   = 'N'
       AND USE_YN   = 'Y'
( PROJECT_CD
						   ,DP_VRSN_ID
						   ,SALES_MGMT_CD
						   ,ITEM_CD
						   ,USER_CD
						   ,PLAN_YYMMDD
						   ,PLAN_WEEK
						   ,PLAN_PART_WEEK
						   ,PLAN_YYMM
						   ,PLAN_YY
						   ,DP_QTY
						   ,CREATE_USER_CD
						   ,CREATE_DATE )

-- 당 주차 계획
    SELECT SMC.PROJECT_CD
        , 'SP_2021W49.01'
        , SMC.SALES_MGMT_CD
        , SMC.ITEM_CD
        , SMC.USER_CD
        , CAL.YYMMDD
        , CAL.WEEK
        , CAL.PART_WEEK
        , CAL.YYMM
        , CAL.YY
        , ISNULL(COPY_VRSN.DP_QTY, 0) DP_QTY
        , 'dev07'
        , getdate()
    FROM M4S_I204050 SMC
      JOIN M4S_I002030 CAL
        ON SMC.PROJECT_CD = CAL.PROJECT_CD
        AND CAL.YYMMDD BETWEEN FORMAT(DATEADD(WEEK, -1, '20211129'), 'yyyyMMdd') AND FORMAT(DATEADD(DAY, -1, '20211129'), 'yyyyMMdd')
        AND CAL.YYMMDD = CAL.START_PART_WEEK_DAY
      LEFT JOIN M4S_O201001 COPY_VRSN
         ON COPY_VRSN.PROJECT_CD = SMC.PROJECT_CD
        AND COPY_VRSN.SALES_MGMT_CD = SMC.SALES_MGMT_CD
        AND COPY_VRSN.ITEM_CD = SMC.ITEM_CD
        AND COPY_VRSN.DP_VRSN_ID = 'SP_2021W41.01'
        AND COPY_VRSN.PLAN_YYMMDD = CAL.YYMMDD
        AND COPY_VRSN.USER_CD = SMC.USER_CD
    WHERE SMC.PROJECT_CD = 'ENT001'
      AND SMC.SALES_MGMT_VRSN_ID = '202111_V0'

-- 지난 3주치 실적
SELECT SMC.PROJECT_CD
        , 'SP_2021W49.01'
        , SMC.SALES_MGMT_CD
        , SMC.ITEM_CD
        , SMC.USER_CD
        , CAL.YYMMDD
        , CAL.WEEK
        , CAL.PART_WEEK
        , CAL.YYMM
        , CAL.YY
        , ISNULL(RST.RST_SALES_QTY, 0) DP_QTY
        , 'dev07'
        , getdate()
    FROM M4S_I204050 SMC
    JOIN M4S_I002030 CAL
        ON SMC.PROJECT_CD = CAL.PROJECT_CD
        AND CAL.YYMMDD BETWEEN FORMAT(DATEADD(WEEK, -4, '20211129'), 'yyyyMMdd') AND FORMAT(DATEADD(DAY, -1, DATEADD(WEEK, -1, '20211129')), 'yyyyMMdd')
        AND CAL.YYMMDD = CAL.START_PART_WEEK_DAY
    LEFT JOIN M4S_I002170_TEST RST
         ON RST.PROJECT_CD = SMC.PROJECT_CD
        AND RST.ITEM_CD = SMC.ITEM_CD
        AND RST.SOLD_CUST_GRP_CD = SUBSTRING(SMC.SALES_MGMT_CD,8,4)
        AND CAL.YYMMDD = RST.YYMMDD
        AND RST.DIVISION_CD = 'SELL_IN'
WHERE SMC.PROJECT_CD = 'ENT001'
    AND SMC.SALES_MGMT_VRSN_ID = '202111_V0'



SELECT * FROM M4S_O201010_1207 WHERE DP_VRSN_ID LIKE 'SP_202111%'
select 193104 /9

delete from m4s_o201001 where DP_VRSN_ID = 'SP_2021W49.01'


INSERT INTO M4S_O201001
SELECT * FROM  TMP_M4S_O201001_TEST WHERE DP_VRSN_ID = 'SP_2021W49.01'

SELECT CAL.START_MONTH_DAY
     FROM M4S_I002030 CAL
, (
         SELECT CASE WHEN START_YN.CNT = 0 THEN 3 ELSE 2 END PLUS_MM
         FROM (
                  SELECT COUNT(*) CNT
                  FROM M4S_I002030
                  WHERE YYMMDD = START_MONTH_DAY
                    AND YYMMDD = '20220801'
              ) START_YN
     ) MM
WHERE 1=1
AND CAL.YYMMDD = FORMAT(DATEADD(MONTH, MM.PLUS_MM, '20220801'),'yyyyMMdd')
GROUP BY CAL.START_MONTH_DAY


select * from m4s_i002030 where yymm = '202201'


SELECT START_MONTH_DAY
     FROM M4S_I002030
	WHERE 1=1
	  AND YYMM = CASE WHEN @WEEK_CNT <= 2 THEN CONVERT(VARCHAR(6),DATEADD(MONTH,3,@FROM_YYMMDD),112)
                      ELSE CONVERT(VARCHAR(6),DATEADD(MONTH,2,@FROM_YYMMDD),112) END
	GROUP BY START_MONTH_DAY


select * from m4s_o201002 where DP_VRSN_ID = 'SP_2021W51.07' and dp_qty != 0


select * from VIEW_I002040